services:
  postgres_db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgresql
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    env_file:
      - .env
    environment:
      DB_HOST: postgres_db
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
 